### PR TITLE
Add links to olm distro packages to README.md

### PR DESCRIPTION
**Pull request by imbev**

### CODE REVIEW

**Comment by HarHarLinks** [comment]
While python-olm would pull in olm over the package manager, at this point I would advise to install libolm instead and leave python packages to whatever python environment someone uses. In distros that have a libolm-dev package split off (e.g. unlike Arch), idk if that is needed.

**Comment by imbev** [comment]
I searched on pkgs.org to find the package names, but I haven't actually tested them.

**Comment by HarHarLinks** [comment]
My point is, instead of searching for `python3-olm` you should have searched for `libolm-dev` because the former is a python package and the other is actual olm
https://ubuntu.pkgs.org/22.04/ubuntu-universe-amd64/libolm-dev_3.2.10~dfsg-6ubuntu1_amd64.deb.html

**Comment by HarHarLinks** [comment]
see https://github.com/i10b/simplematrixbotlib/pull/147/commits/fafb6a8e8241e30668d8d03977b8b4ca1b706e2d

**Pull request closed without merging**
